# fly.toml app configuration file for Telegram bot on Fly.io

app = "rewardsbots"
primary_region = "phx"

[build]

[processes]
  app = "node index.js"

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024