# fly.toml app configuration file for Telegram bot on Fly.io

app = "rewardsbots"
primary_region = "phx"

[build]

[processes]
  app = "node index.js"  # Your bot's start command

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[http_service]  # Add this section to prevent auto-stop and keep the app running
  internal_port = 3000
  force_https = true
  auto_stop_machines = "never"  # Disable auto-stop, keep the bot running 24/7
  auto_start_machines = true
  min_machines_running = 1  # Keep at least 1 machine running
  processes = ["app"]